### ISSUE TITLE
Missing Modules/paths for running `Validation_Ian.ipynb`

### ISSUE THREAD

**Issue by FariborzDaneshvar-NOAA** [SorooshMani-NOAA/OCSMeshTutorial#7]
@SorooshMani-NOAA and @yunfangsun I am running the [Validation_Ian.ipynb](https://github.com/SorooshMani-NOAA/OCSMeshTutorial/blob/main/Tutorials_2023/Validation_Ian.ipynb) standalone and getting an error for missing modules
```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 5
      1 PathToMyFunctions = Path('.').absolute() / 'utility'
      3 sys.path.append(str(PathToMyFunctions))
----> 5 from SchismFunctions import read_SchismWaterElevation2D
      6 from SchismFunctions import read_ObservedWaterLevel
      7 from PythonFunctions import find_indices2D

ModuleNotFoundError: No module named 'SchismFunctions'
```

I also see some paths in the next cells (i.e. `Path_pahmc = workdir / 'pahmc/outputs'`) that I don't have either. Can you please help me to resolve these issues?

**Comment by SorooshMani-NOAA** [comment]
@FariborzDaneshvar-NOAA these notebooks need some scripts from Bahram. I'll share them with you on PW. We haven't figured out how we'd like to share these scripts for the tutorials with the public

**Comment by yunfangsun** [comment]
@FariborzDaneshvar-NOAA 

`Path_pahmc = workdir / 'pahmc/outputs' ` is the model simulation results

**Comment by SorooshMani-NOAA** [comment]
@FariborzDaneshvar-NOAA see `/lustre/Soroosh/from_Bahram/my_schism_utility/utility_functions` on the shared cluster for missing modules

**Comment by SorooshMani-NOAA** [comment]
@FariborzDaneshvar-NOAA the datasets for this notebook are not shared yet, so please feel free to modify to match your usecase. It is **not** self contained.

**Comment by FariborzDaneshvar-NOAA** [comment]
Thank you @SorooshMani-NOAA  and @yunfangsun  for your responses!
